Html templating fix after review
ajaxtown/linkcast pull request #20
Opened 2017-09-04 11:45 UTC by bi6o

Worked on the changes you have suggested

2017-09-04 12:01 UTC, ajaxtown commented on dev/view/popup_dev.html
> +            <!-- view/notification.html  -->
`view/notification.html` - this file does not exist.

2017-09-04 12:03 UTC, abhisaha1 requested changes
Almost done. You forgot to add the file `view/notification.html`

2017-09-04 12:19 UTC, bi6o commented
Moved the template into popup_dev and removed the file

2017-09-04 13:21 UTC, ajaxtown commented on dev/view/templates/notification.html
> -</div>
why did you delete this ? This is the template of the notification item.

2017-09-04 13:23 UTC, ajaxtown commented on dev/view/popup_dev.html
> +            </div>
This should contain the notification view.
```
<div class="scroll tab-pane fade active in" id="tab-notifications">
                <div class="items user-enabled">
                    <div id="loader" class="preloader"><img src="public/images/loader.svg"></div>
                </div>
            </div>
```

2017-09-04 13:23 UTC, abhisaha1 requested changes
Check my comments

2017-09-05 13:27 UTC, ajaxtown commented
Closing this PR as it was cloned and fixed and merged.

2017-09-05 13:27 UTC, closed without merging